import { useState } from 'react';
import { ChevronLeft } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import EmptyState from '../components/ui/EmptyState';
import { useAuthStore } from '../store/authStore';
import { useMembershipStore } from '../store/membershipStore';

export default function MembershipSetupPage(){
  const navigate=useNavigate(); const [params]=useSearchParams(); const currentUser=useAuthStore(s=>s.currentUser); const {createOrganization,joinOrganization,selectMembership}=useMembershipStore();
  const [mode,setMode]=useState(params.get('action')==='join'?'join':'create'); const [name,setName]=useState(''); const [groupName,setGroupName]=useState(''); const [code,setCode]=useState(''); const [error,setError]=useState('');
  const [saving,setSaving]=useState(false);
  if(!currentUser)return <EmptyState title="로그인이 필요합니다."/>;
  const complete=async()=>{if(saving)return;if(mode==='create'&&!name.trim()){setError('기관명 또는 그룹명을 입력해 주세요.');return;}if(mode==='join'&&!code.trim()){setError('초대 코드를 입력해 주세요.');return;}setSaving(true);setError('');try{const membership=mode==='create'?await createOrganization(currentUser.id,name,'OWNER',groupName):await joinOrganization(currentUser.id,code);if(!membership){setError('초대 코드를 확인해 주세요.');return;}selectMembership(membership.id);navigate('/',{replace:true});}catch{setError(mode==='create'?'소속을 만들지 못했습니다. 네트워크 연결을 확인하고 다시 시도해 주세요.':'초대 코드를 확인하지 못했습니다. 네트워크 연결을 확인하고 다시 시도해 주세요.');}finally{setSaving(false);}};
  return <div className="page-container bg-[#F8F5F0]"><main className="min-h-[100dvh] px-5 pb-8 pt-[max(1rem,env(safe-area-inset-top))]"><button onClick={()=>navigate(-1)} className="flex h-11 w-11 items-center justify-center" aria-label="뒤로 가기"><ChevronLeft size={20}/></button><h1 className="mt-5 text-2xl font-bold text-[#14233B]">소속 추가</h1><div className="mt-6 grid grid-cols-2 rounded-[10px] bg-[#EEE9E2] p-1"><button onClick={()=>{setMode('create');setError('');}} className={`min-h-10 rounded-[8px] text-xs font-bold ${mode==='create'?'bg-[#FFFDFC] text-[#14233B] shadow-sm':'text-[#7D8490]'}`}>새 소속 만들기</button><button onClick={()=>{setMode('join');setError('');}} className={`min-h-10 rounded-[8px] text-xs font-bold ${mode==='join'?'bg-[#FFFDFC] text-[#14233B] shadow-sm':'text-[#7D8490]'}`}>초대 코드 입력</button></div>{mode==='create'?<section className="mt-6 space-y-3"><label className="block text-xs font-bold text-[#53606F]">기관명 또는 그룹명<input value={name} onChange={e=>setName(e.target.value)} placeholder="예: 미술 학원" className="mt-2 min-h-12 w-full rounded-[9px] border border-[#DED7CE] bg-[#FFFDFC] px-4 text-sm"/></label><label className="block text-xs font-bold text-[#53606F]">첫 반 이름 · 선택<input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="예: 수채화반" className="mt-2 min-h-12 w-full rounded-[9px] border border-[#DED7CE] bg-[#FFFDFC] px-4 text-sm"/></label><div className="rounded-[10px] bg-[#F1E7D6] p-3 text-xs text-[#806332]">기본 역할: 운영자(OWNER)</div></section>:<section className="mt-6"><label className="block text-xs font-bold text-[#53606F]">초대 코드<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="6자리 코드" className="mt-2 min-h-12 w-full rounded-[9px] border border-[#DED7CE] bg-[#FFFDFC] px-4 text-center text-base font-bold tracking-[.2em]"/></label><p className="mt-3 text-xs leading-5 text-[#687282]">코드 확인 후 연결될 소속과 학생 역할로 참여합니다.</p></section>}{error&&<p role="alert" className="mt-4 rounded-[8px] bg-[#F7ECEA] p-3 text-xs text-[#A65F59]">{error}</p>}<button onClick={complete} disabled={saving} className="mt-8 min-h-12 w-full rounded-[9px] bg-[#14233B] text-sm font-bold text-white disabled:opacity-50">{saving?'처리 중...':mode==='create'?'소속 만들기':'참여 완료'}</button></main></div>;
}
