import { Building2, ChevronRight, Clock3, KeyRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';

export default function RoleSelectionPage(){
  const navigate=useNavigate();
  const {pendingSocialProfile,currentUser,completeSocialRegistration,clearPendingProfile}=useAuthStore();
  const prepare=async(path:string)=>{if(!currentUser){if(!pendingSocialProfile)return;await completeSocialRegistration('TEACHER');}navigate(path,{replace:true});};
  if(!pendingSocialProfile&&!currentUser){navigate('/signup',{replace:true});return null;}
  const name=pendingSocialProfile?.name??currentUser?.name;
  return <div className="page-container bg-[#F8F5F0]"><main className="flex min-h-[100dvh] flex-col px-6 pb-8 pt-[max(2rem,env(safe-area-inset-top))]"><div className="serif-brand text-[44px]">M</div><section className="mt-10"><h1 className="text-2xl font-bold text-[#14233B]">{name}님, 다음 단계를 선택하세요.</h1><p className="mt-2 text-sm leading-6 text-[#687282]">계정은 역할 하나로 고정되지 않습니다.<br/>소속마다 다른 역할로 참여할 수 있어요.</p></section><div className="mt-8 space-y-3"><button onClick={()=>prepare('/onboarding?action=create')} className="flex min-h-20 w-full items-center gap-4 rounded-[13px] border border-[#D8D0C5] bg-[#FFFDFC] p-4 text-left"><Building2 className="text-[#B58A4A]"/><span className="flex-1"><strong className="block text-sm text-[#14233B]">새 소속 만들기</strong><span className="mt-1 block text-xs text-[#687282]">기관을 만들고 운영자로 시작</span></span><ChevronRight size={17}/></button><button onClick={()=>prepare('/onboarding?action=join')} className="flex min-h-20 w-full items-center gap-4 rounded-[13px] border border-[#D8D0C5] bg-[#FFFDFC] p-4 text-left"><KeyRound className="text-[#B58A4A]"/><span className="flex-1"><strong className="block text-sm text-[#14233B]">초대 코드로 소속 참여</strong><span className="mt-1 block text-xs text-[#687282]">연결될 소속과 역할 확인</span></span><ChevronRight size={17}/></button><button onClick={()=>prepare('/memberships')} className="flex min-h-16 w-full items-center gap-4 rounded-[13px] border border-[#E7E1D9] bg-transparent p-4 text-left"><Clock3 className="text-[#8B929C]"/><span className="flex-1 text-sm font-semibold text-[#53606F]">나중에 설정하기</span><ChevronRight size={17}/></button></div><button onClick={()=>{clearPendingProfile();navigate('/start',{replace:true});}} className="mt-auto min-h-12 text-xs font-semibold text-[#687282]">시작 화면으로</button></main></div>;
}
