import { Copy, Mail, Pencil, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { useState } from 'react';
import Modal from '../ui/Modal';
import type { GuardianRelationship } from '../../types';
import { useGuardianStore } from '../../store/guardianStore';

const relationships: GuardianRelationship[] = ['어머니', '아버지', '조부모', '보호자', '기타'];

export default function GuardianManagementSection({ organizationId, studentId, studentName }: { organizationId: string; studentId: string; studentName: string }) {
  const { guardians, links, upsertGuardian, unlinkGuardian } = useGuardianStore();
  const studentLinks = links.filter((link) => link.organizationId === organizationId && link.studentId === studentId && link.status === 'ACTIVE');
  const [open, setOpen] = useState(false);
  const [editingId, setEditingId] = useState<string>();
  const [name, setName] = useState('');
  const [relationship, setRelationship] = useState<GuardianRelationship>('어머니');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [primary, setPrimary] = useState(false);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState('');

  const reset = () => { setEditingId(undefined); setName(''); setRelationship('어머니'); setPhone(''); setEmail(''); setPrimary(studentLinks.length === 0); setNotice(''); };
  const add = () => { reset(); setOpen(true); };
  const edit = (guardianId: string) => { const guardian = guardians.find((item) => item.id === guardianId); const link = studentLinks.find((item) => item.guardianId === guardianId); if (!guardian || !link) return; setEditingId(guardian.id); setName(guardian.name); setRelationship(link.relationship); setPhone(guardian.phone ?? ''); setEmail(guardian.email ?? ''); setPrimary(link.isPrimary); setNotice(''); setOpen(true); };
  const save = async () => { if (!name.trim() || saving) return; setSaving(true); setNotice(''); try { await upsertGuardian(organizationId, { id: editingId, studentId, name, relationship, phone, email, isPrimary: primary }); setOpen(false); reset(); } catch { setNotice('보호자 정보를 저장하지 못했습니다. 다시 시도해 주세요.'); } finally { setSaving(false); } };
  const unlink = async (guardianId: string) => { if (!window.confirm('이 학생과 보호자 연결을 해제할까요?')) return; try { await unlinkGuardian(organizationId, studentId, guardianId); } catch { setNotice('연결을 해제하지 못했습니다.'); } };
  const invite = async (guardianId: string) => { const guardian = guardians.find((item) => item.id === guardianId); const url = `${window.location.origin}/signup`; const text = `${studentName} 학생 보호자 계정 안내\n${guardian?.email ? `${guardian.email}로 ` : ''}가입하면 연결된 리포트를 확인할 수 있습니다.\n${url}`; try { await navigator.clipboard.writeText(text); setNotice('보호자 가입 안내를 복사했습니다. 등록한 이메일로 가입해야 자동 연결됩니다.'); } catch { setNotice(`가입 주소: ${url}`); } };

  return <section>
    <div className="mb-3 flex items-center justify-between"><div><h2 className="text-[17px] font-semibold text-[#14233B]">보호자</h2><p className="mt-1 text-[10px] text-[#8B929C]">개인정보는 운영자만 수정할 수 있습니다.</p></div><button onClick={add} className="flex min-h-11 items-center gap-1 text-xs font-bold text-[#14233B]"><Plus size={15}/>보호자 추가</button></div>
    <div className="space-y-2">{studentLinks.map((link) => { const guardian = guardians.find((item) => item.id === link.guardianId); if (!guardian) return null; return <article key={link.id} className="rounded-[13px] border border-[#E1DBD3] bg-[#FFFDFC] p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#F1E7D6] text-[#9A7138]"><ShieldCheck size={18}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><strong className="text-sm text-[#14233B]">{guardian.name}</strong><span className="text-xs text-[#687282]">· {link.relationship}</span>{link.isPrimary && <span className="rounded-full bg-[#EDF4EF] px-2 py-0.5 text-[9px] font-bold text-[#4F8A68]">주 보호자</span>}</div><p className="mt-1 text-[11px] text-[#8B929C]">{guardian.phone || '전화번호 미등록'}{guardian.email ? ` · ${guardian.email}` : ''}</p><p className="mt-1 text-[10px] text-[#8B929C]">{guardian.authUserId ? '계정 연결됨' : '계정 미연결'}</p></div></div><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={() => edit(guardian.id)} className="flex min-h-10 items-center justify-center gap-1 rounded-[9px] border border-[#D8D0C5] text-[11px] font-bold text-[#53606F]"><Pencil size={12}/>수정</button><button onClick={() => void invite(guardian.id)} className="flex min-h-10 items-center justify-center gap-1 rounded-[9px] border border-[#D8D0C5] text-[11px] font-bold text-[#53606F]">{guardian.email ? <Mail size={12}/> : <Copy size={12}/>}초대</button><button onClick={() => void unlink(guardian.id)} className="flex min-h-10 items-center justify-center gap-1 rounded-[9px] border border-[#E4C5C2] text-[11px] font-bold text-[#A65F59]"><Trash2 size={12}/>해제</button></div></article>; })}{studentLinks.length === 0 && <div className="rounded-[12px] border border-dashed border-[#D8D0C5] bg-[#FFFDFC] px-4 py-5 text-center"><p className="text-xs text-[#8B929C]">연결된 보호자가 없습니다.</p><button onClick={add} className="mt-2 min-h-10 text-xs font-bold text-[#14233B]">첫 보호자 추가</button></div>}</div>
    {notice && <p role="status" className="mt-2 rounded-[9px] bg-[#F5F2ED] px-3 py-2 text-[11px] font-semibold text-[#53606F]">{notice}</p>}
    <Modal isOpen={open} onClose={() => setOpen(false)} title={editingId ? '보호자 수정' : '보호자 추가'}><div className="space-y-4"><label className="block text-xs font-bold text-[#53606F]">이름<input value={name} onChange={(event) => setName(event.target.value)} maxLength={80} placeholder="보호자 이름" className="mt-2 min-h-12 w-full rounded-[10px] border border-[#D8D0C5] px-3 text-sm"/></label><label className="block text-xs font-bold text-[#53606F]">관계<select value={relationship} onChange={(event) => setRelationship(event.target.value as GuardianRelationship)} className="mt-2 min-h-12 w-full rounded-[10px] border border-[#D8D0C5] bg-white px-3 text-sm">{relationships.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-xs font-bold text-[#53606F]">전화번호 · 선택<input value={phone} onChange={(event) => setPhone(event.target.value)} maxLength={30} inputMode="tel" placeholder="010-0000-0000" className="mt-2 min-h-12 w-full rounded-[10px] border border-[#D8D0C5] px-3 text-sm"/></label><label className="block text-xs font-bold text-[#53606F]">이메일 · 계정 연결용<input value={email} onChange={(event) => setEmail(event.target.value)} maxLength={254} type="email" placeholder="guardian@example.com" className="mt-2 min-h-12 w-full rounded-[10px] border border-[#D8D0C5] px-3 text-sm"/><span className="mt-1 block text-[10px] font-normal leading-4 text-[#8B929C]">보호자가 같은 이메일로 가입하면 자동 연결됩니다.</span></label><label className="flex min-h-12 items-center gap-3 rounded-[10px] bg-[#F5F2ED] px-3"><input type="checkbox" checked={primary} onChange={(event) => setPrimary(event.target.checked)} className="h-5 w-5 accent-[#14233B]"/><span className="text-sm font-semibold text-[#14233B]">주 보호자로 설정</span></label>{notice && <p role="alert" className="text-xs text-[#A65F59]">{notice}</p>}<div className="flex gap-2"><button onClick={() => setOpen(false)} className="min-h-12 flex-1 rounded-[10px] border border-[#D8D0C5] text-sm font-bold text-[#687282]">취소</button><button onClick={() => void save()} disabled={!name.trim() || saving} className="min-h-12 flex-1 rounded-[10px] bg-[#14233B] text-sm font-bold text-white disabled:opacity-40">{saving ? '저장 중...' : '저장'}</button></div></div></Modal>
  </section>;
}
